WIU-176 #comment bugfix: DockingManager serialization
JDLabOrg/wpftoolkit pull request #14
Opened 2018-03-05 06:49 UTC by DongHyeon-JDLab

2018-03-05 07:41 UTC, seungmi commented on ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Layout/LayoutRoot.cs
>          {
해당 내용이 바뀌어도 상관없는건가요?
구조 바뀐것을 정확하게 모르겠어요 
우선 change_LOG 파일도 같이 작성 부탁드립니다.

2018-03-05 07:41 UTC, seungmi commented on ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Controls/OverlayWindow.cs
> +                                /*
이 부분은 다 소용없는건가요??

2018-03-05 08:09 UTC, DongHyeon-JDLab commented on ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Layout/LayoutRoot.cs
>          {
네 바뀌어야 정상동작합니다
기존버전이 제대로 동작을 안해요

2018-03-05 08:11 UTC, DongHyeon-JDLab commented on ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Controls/OverlayWindow.cs
> +                                /*
네 Document쪽에 다른 Layout은 못들어오게하려고 주석처리했습니다

2018-03-06 07:42 UTC, ghost requested changes

2018-03-06 07:42 UTC, seungmi commented on ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Layout/LayoutRoot.cs
> +
///@note RootPanel -> LayoutPanel <xml tag> 주석만 처리해주세요~

2018-03-06 10:19 UTC, DongHyeon-JDLab commented on ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Layout/LayoutRoot.cs
> +
CHANGLOG & comment 추가완료

2018-03-07 08:13 UTC, ghost approved these changes

2018-03-08 01:35 UTC, merged